GRANT SELECT, INSERT, UPDATE, DELETE ON public.teams TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.applications TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_updates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.incidents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.incident_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calls TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.learnings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analyses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.blockers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tomorrow_plans TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated;
GRANT SELECT, INSERT ON public.activity_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.manager_comments TO authenticated;

GRANT ALL ON public.teams TO service_role;
GRANT ALL ON public.applications TO service_role;
GRANT ALL ON public.profiles TO service_role;
GRANT ALL ON public.user_roles TO service_role;
GRANT ALL ON public.daily_updates TO service_role;
GRANT ALL ON public.daily_tasks TO service_role;
GRANT ALL ON public.incidents TO service_role;
GRANT ALL ON public.incident_participants TO service_role;
GRANT ALL ON public.calls TO service_role;
GRANT ALL ON public.learnings TO service_role;
GRANT ALL ON public.analyses TO service_role;
GRANT ALL ON public.blockers TO service_role;
GRANT ALL ON public.tomorrow_plans TO service_role;
GRANT ALL ON public.notifications TO service_role;
GRANT ALL ON public.activity_logs TO service_role;
GRANT ALL ON public.manager_comments TO service_role;

GRANT EXECUTE ON FUNCTION public.ensure_profile(text, app_role, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_team_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.team_of(uuid) TO authenticated;